# Copyright 2026 Christian Garay

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

server.port=8000
spring.application.name=foro-hub

# ==========================================
# CONFIGURACION DE CONEXION (ORACLE 26ai)
# ==========================================
# La ruta usa ${user.dir} para que funcione en cualquier PC donde descargues el proyecto
spring.datasource.url=jdbc:oracle:thin:@forohubdb_high?TNS_ADMIN=/home/ubuntu/Wallet_forohubdb
#"src/main/resources/oracle_wallet"
spring.datasource.username=ADMIN
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==========================================
# CONFIGURACION DE JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Reintentos de conexi\u00F3n para Hikari CP
spring.datasource.hikari.initialization-fail-timeout=0

# Logs y Consola
logging.level.org.springframework.aop.framework.CglibAopProxy=WARN
spring.output.ansi.enabled=always


# Seguridad
jwt.secret=${JWT_SECRET:mi_clave_secreta_super_larga_y_segura_1234567890}

# ==========================================
# CONFIGURACION DE IA (Google & Mistral)
# ==========================================
spring.ai.google.genai.project-id=${PROJECT_ID}
spring.ai.google.genai.api-key=${GEMINI_APIKEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview

spring.ai.mistralai.api-key=${MISTRAL_API_KEY}

# Optimizaciones de Logs y Observabilidad para IA
logging.level.org.springframework.ai = OFF
logging.level.com.google.genai = OFF
logging.level.org.springframework.retry = OFF
spring.ai.retry.max-attempts = 1
spring.ai.google.genai.chat.options.timeout = 3000ms
spring.ai.chat.client.enabled=false
spring.ai.chat.observations.enabled=false
spring.ai.image.observations.enabled=false
management.observations.enable=false
spring.ai.vectorstore.observations.enabled=false

# ==========================================
# CONFIGURACION DE SWAGGER
# ==========================================
springdoc.swagger-ui.path=/api/swagger-ui.html
#/api/swagger-ui/index.html
springdoc.swagger-ui.use-root-path=false
#true
springdoc.api-docs.path=/v3/api-docs

spring.data.web.pageable.serialization-mode=via-dto

# ==========================================
# CONFIGURACION PARA LOAD BALANCER (Proxy)
# ==========================================
#server.forward-headers-strategy=native
#server.tomcat.remoteip.remote-ip-header=x-forwarded-for
#server.tomcat.remoteip.protocol-header=x-forwarded-proto

# ==========================================
# CONFIGURACION PARA ORACLE CLOUD
# ==========================================
oracle.cloud.bucket.name=${OCI_BUCKET_NAME:imagenes-foro-hub}
oracle.cloud.namespace=${OCI_NAMESPACE:}
oracle.cloud.fingerprint=${OCI_FINGERPRINT}
oracle.cloud.user-id=${OCI_USER_ID}
oracle.cloud.tenancy-id=${OCI_TENANCY_ID}
oracle.cloud.region=${OCI_REGION:sa-santiago-1}
oracle.cloud.private-key-path=${OCI_PRIVATE_KEY_PATH}
# Desactiva los hilos de diagnostico de Oracle que causan los WARN en el reinicio
oracle.jdbc.diagnostic.Diagnostic.CLOCK=false

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# Permitir hasta 5MB por foto (equilibrio entre calidad y peso)
spring.servlet.multipart.max-file-size=5MB

# Limite total de la peticion
spring.servlet.multipart.max-request-size=5MB